### ISSUE TITLE
ERROR Invalid template name

### ISSUE THREAD

**Issue by hill84** [dkundel/create-project#2]
I tried following your [tutorial](https://www.twilio.com/blog/how-to-build-a-cli-with-node-js) and it gives me this error in the terminal: `ERROR Invalid template name`. 
I also tried installing your package as it is... with the same result.

**Comment by hill84** [comment]
The issue was related to the definition of templateDir. I have found a solution defining templateDir as follow: 

```
const templateDir = path.resolve(
    new URL(currentFileUrl).pathname.substring(new URL(currentFileUrl).pathname.indexOf('/')+1),
    '../../templates',
    options.template.toLowerCase()
  );
```

**Comment by Fox333-Lab** [comment]
> The issue was related to the definition of templateDir. I have found a solution defining templateDir as follow:
> 
> ```
> const templateDir = path.resolve(
>     new URL(currentFileUrl).pathname.substring(new URL(currentFileUrl).pathname.indexOf('/')+1),
>     '../../templates',
>     options.template.toLowerCase()
>   );
> ```


Adding " **+1** " to the index worked for me 👍
